### PR TITLE
Add support for generating Type Aliases

### PR DESCRIPTION
**Pull request by bmoylan**
@dpolansky this commit adds an `AliasSpec` type for statements like `type ID string`.

---
This change is [Reviewable](https://reviewable.io/reviews/dpolansky/go-poet/4)

### CODE REVIEW

**Comment by dpolansky** [comment]
Generating type aliases completely slipped our minds -- this is great. I think naming it `TypeAliasSpec` would be more clear, would you mind changing that? Other than that, lgtm.

**Comment by bmoylan** [comment]
Agreed, done.

As a heads up, I have a few more changes coming in shortly. I'm also looking to eventually tackle #2. This is a great library, thanks for maintaining it!

**Comment by dpolansky** [comment]
Awesome! Looking forward to them. Thanks for the help!

**Comment by dpolansky** [comment]
@bmoylan Feel free to post ideas in #2, we haven't thought of an elegant solution to it yet.

**Comment by kdeenanauth** [comment]
For generating type aliases, it would be nice to have an example in the `README.md`

**Pull request merged**
